# Generated by Django 4.0 on 2021-12-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_yorummodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yorummodel',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelTable(
            name='yorummodel',
            table='yorum',
        ),
    ]
